### ISSUE TITLE
randomized movements for a comprehensive functionality test

### ISSUE THREAD

**Issue by leyuan-sun** [gramuah/vsn_rr#2]
How does this random walking strategy to decide if the agent find the goal? Is there any object detection inside the pipeline?

**Comment by rlopezsastre** [comment]
No, there is no integrated object detector.
It is simply a demonstrator to test the discrete motion commands on the platforms, once the whole software package is integrated.

**Comment by leyuan-sun** [comment]
I see, it is just a movement scripts instead of a random walking policy for navigation task.
